/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/testair.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TestAir(props) {
  const { nodes, materials } = useGLTF('./models/testair.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_062001.geometry} material={materials.Material} position={[-2.986, 4.622, 0.008]} />
    </group>
  )
}

useGLTF.preload('./models/testair.gltf')
